// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import database "github.com/matthew-j-welte/bit-board/server/database"
import mock "github.com/stretchr/testify/mock"

// DBHelper is an autogenerated mock type for the DBHelper type
type DBHelper struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *DBHelper) Client() database.ClientHelper {
	ret := _m.Called()

	var r0 database.ClientHelper
	if rf, ok := ret.Get(0).(func() database.ClientHelper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.ClientHelper)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *DBHelper) Collection(name string) database.CollectionHelper {
	ret := _m.Called(name)

	var r0 database.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) database.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.CollectionHelper)
		}
	}

	return r0
}

// GetCollection provides a mock function with given fields: name
func (_m *DBHelper) GetCollection(name string) database.CollectionHelper {
	ret := _m.Called(name)

	var r0 database.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) database.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.CollectionHelper)
		}
	}

	return r0
}
