// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import resources "github.com/matthew-j-welte/bit-board/server/models/resources"

// LearningSuggestionDB is an autogenerated mock type for the LearningSuggestionDB type
type LearningSuggestionDB struct {
	mock.Mock
}

// Create provides a mock function with given fields: resource, userID
func (_m *LearningSuggestionDB) Create(resource resources.ResourceSuggestion, userID string) (string, error) {
	ret := _m.Called(resource, userID)

	var r0 string
	if rf, ok := ret.Get(0).(func(resources.ResourceSuggestion, string) string); ok {
		r0 = rf(resource, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(resources.ResourceSuggestion, string) error); ok {
		r1 = rf(resource, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
