// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import primitive "go.mongodb.org/mongo-driver/bson/primitive"

// ManyResultsHelper is an autogenerated mock type for the ManyResultsHelper type
type ManyResultsHelper struct {
	mock.Mock
}

// Decode provides a mock function with given fields:
func (_m *ManyResultsHelper) Decode() ([]primitive.M, error) {
	ret := _m.Called()

	var r0 []primitive.M
	if rf, ok := ret.Get(0).(func() []primitive.M); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]primitive.M)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
