containerPort: 5002

localdbEnv: development

image:
  repository: sentraindev.azurecr.io/development/mwelte/member-tracker
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-dev-secret

service:
  port: 5002
  targetPort: 5002
  type: NodePort
  nodePort: 30002

environment:
  - name: ASPNETCORE_URLS
    value: http://+:5002
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
    value: "false"
  - name: SENTRAIN_PATH
    value: /data
