containerPort: 5000

localdbEnv: integration

image:
  repository: sentraindev.azurecr.io/integration/mwelte/challenge-tracker
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-dev-secret

service:
  port: 5000
  targetPort: 5000
  type: NodePort
  nodePort: 30000

environment:
  - name: ASPNETCORE_URLS
    value: http://+:5000
  - name: ASPNETCORE_ENVIRONMENT
    value: Integration
  - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
    value: "false"
  - name: CACHING_DISABLED
    value: true
  - name: SENTRAIN_PATH
    value: /data

cronjobs:
  crons:
    - name: challenge-completer-est
      command: some dotnet startup
      scheduler: 59 3 * * *
      replicas: 1
    - name: challenge-completer-ct
      command: some dotnet startup
      scheduler: 59 4 * * *
      replicas: 1
    - name: challenge-completer-mt
      command: some dotnet startup
      scheduler: 59 5 * * *
      replicas: 1
    - name: challenge-completer-pst
      command: some dotnet startup
      scheduler: 59 6 * * *
      replicas: 1
