home = "http://localhost:3000/"
newExercise = "http://localhost:3000/exercise/new/"
editExercise = "http://localhost:3000/exercise/edit/"
prePublish = "http://localhost:3000/exercise/pre-publish/"
myPublishRequestsPage = "http://localhost:3000/publish-requests/mine/"
adminPublishRequestsPage = "http://localhost:3000/admin/publish-requests-review/"

getExercise = "http://localhost:5001/exercise/get/"
postNewExercise = "http://localhost:5001/exercise/new"
searchMyExerciseLinks = "http://localhost:5001/exercise/search/links/0/"
searchPublishedExerciseLinks = "http://localhost:5001/exercise/search/links/1/"
searchAllExerciseLinks = "http://localhost:5001/exercise/search/links/2/"
getMyPublishRequests = "http://localhost:5001/exercise/publish-requests/"
getAllExerciseLinks = "http://localhost:5001/exercise/search/all-links/"

adminGetPublishRequests = "http://localhost:5001/exercise/admin-publish-requests/"
prePublish = "http://localhost:5001/exercise/pre-publish"
